{"id": "5340", "title": "Bug 5340 Cancelling add exception breakpoint has no effect", "description": "", "OB": "When attempting to cancel the process of adding an exception breakpoint, the progress dialog closes immediately. However, even after the cancellation request, the exception list eventually comes up. This behavior ignores the cancellation request.", "EB": "The progress dialog should not close immediately when cancelling the addition of an exception breakpoint. It should either honor the cancellation request or disable the cancel button. To achieve this, when calling ProgressMonitorDialog.run, the 'cancellable' parameter should be set to false.", "SR": "To reproduce the issue: \n1. Open the program and navigate to the breakpoint settings. \n2. Begin the process of adding an exception breakpoint. \n3. While the progress dialog is open, click the cancel button. \n4. Observe that the progress dialog closes immediately, but the exception list still appears despite the cancellation request."}