{"id": "5340", "title": "Bug 5340: Cancelling add exception breakpoint has no effect", "description": "", "OB": "When adding an exception breakpoint, if the user cancels the operation in the progress dialog, the dialog closes immediately and eventually the exception list comes up. It appears that the cancellation request is being ignored. The cancel button should either be disabled or the cancellation request should be honored. Currently, when calling ProgressMonitorDialog.run, the 'cancellable' parameter is not being set to false.", "EB": "The progress dialog should honor the cancellation request by either disabling the cancel button or setting the 'cancellable' parameter to false when calling ProgressMonitorDialog.run.", "SR": "To reproduce the issue: \n1) Go to the breakpoints pane in the debug perspective. \n2) Click the 'J!' button to add an exception breakpoint. \n3) In the progress dialog, click cancel."}