{"id": "121687", "title": "Bug 121687: Exception thrown when exporting data in table inside a grid cell", "description": "", "OB": "When exporting data in a table that is inside a grid cell, an exception is thrown.", "EB": "When exporting data in two tables, the expected result is that the data are exported. However, the actual result is that an exception occurs in the ReportEngineService.getMetaData() function.", "SR": "To reproduce this issue, follow these steps:\n1. Insert a grid.\n2. Export data in the table that is inside a grid cell."}