{"id": "121687", "title": "Bug 121687: Exception thrown when exporting data in table inside a grid cell", "description": "", "OB": "The bug report does not provide any information about the observed behavior.", "EB": "When exporting data in two tables, the expected result is that the data is exported successfully. However, the actual result is that an exception is thrown in the 'ReportEngineService.getMetaData()' method.", "SR": "1. Open the application\n2. Navigate to the grid cell containing a table\n3. Attempt to export the data in the table\n4. Observe that an exception is thrown in the 'ReportEngineService.getMetaData()' method"}